"""Script one-shot para atualizar o node RAG do workflow n8n (PR6 #4)."""
import json, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
WF_PATH = ROOT / "n8n_workflow_contestar_por_peticao.json"

NEW_JS = (
    "// n8n 2.17.5 JS sandbox shims (process, AbortController, fetch). Tudo em const.\n"
    "const __AC_INIT = (() => { if (typeof globalThis.AbortController === 'undefined') { globalThis.AbortController = class { constructor() { this.signal = undefined; } abort() {} }; } return true; })();\n"
    "const __PROC = (() => { try { return process.env || {}; } catch (_) { return {}; } })();\n"
    "const __HTTP = (() => { try { if ($helpers && $helpers.httpRequest) return $helpers; } catch (_) {} try { if (typeof helpers !== 'undefined' && helpers && helpers.httpRequest) return helpers; } catch (_) {} try { if (this && this.helpers && this.helpers.httpRequest) return this.helpers; } catch (_) {} return null; })();\n"
    "const __FETCH = async (url, opts) => {\n"
    "  opts = opts || {};\n"
    "  const method = opts.method || 'GET';\n"
    "  const headers = opts.headers || {};\n"
    "  let body = opts.body;\n"
    "  if (typeof body === 'string') { try { body = JSON.parse(body); } catch (_) { /* mantem string */ } }\n"
    "  if (!__HTTP) {\n"
    "    try { const r = await fetch(url, opts); return r; } catch (_) {}\n"
    "    throw new Error('http_unavailable: nem $helpers.httpRequest nem fetch global no sandbox');\n"
    "  }\n"
    "  try {\n"
    "    const r = await __HTTP.httpRequest({ url, method, headers, body, json: true, returnFullResponse: true, ignoreHttpStatusErrors: true });\n"
    "    const status = r.statusCode || r.status || 200;\n"
    "    const data = (r.body !== undefined) ? r.body : r;\n"
    "    return {\n"
    "      ok: status >= 200 && status < 300, status,\n"
    "      json: async () => data,\n"
    "      text: async () => (typeof data === 'string' ? data : JSON.stringify(data || {})),\n"
    "    };\n"
    "  } catch (e) {\n"
    "    const status = e.statusCode || e.status || 500;\n"
    "    const msg = (e.message || '').slice(0, 500);\n"
    "    return { ok: false, status, json: async () => ({ error: msg }), text: async () => msg };\n"
    "  }\n"
    "};\n"
    "\n"
    "const envelope = $input.first().json;\n"
    "if (envelope.status === 'erro_validacao') {\n"
    "  return [{ json: envelope }];\n"
    "}\n"
    "\n"
    "const dados = envelope.dados_extraidos || {};\n"
    "\n"
    "const readEnv = (key, fb = '') => {\n"
    "  try {\n"
    "    if (typeof $vars !== 'undefined' && $vars && $vars[key]) return String($vars[key]).trim();\n"
    "    return ($env && $env[key]) ? String($env[key]).trim() : (__PROC[key] || fb);\n"
    "  } catch { return __PROC[key] || fb; }\n"
    "};\n"
    "\n"
    "const SAFE_TIPO_RX = /^[\\w\\s\\u00C0-\\u00FF\\-().]{1,100}$/;\n"
    "const SAFE_NUMERO_RX = /^[\\w\\-./]{1,40}$/;\n"
    "const tipoRaw = String(dados.tipo_acao || '').trim();\n"
    "const numeroRaw = String(dados.numero_processo || 'sem-numero').trim();\n"
    "\n"
    "const BACKEND_URL = readEnv('BACKEND_URL', 'http://autojuri_backend:8000');\n"
    "const ADMIN_TOKEN = readEnv('BACKEND_ADMIN_TOKEN', '');\n"
    "\n"
    "// PR6 #4 RAG Semantico: tenta backend primeiro (pgvector <=>), cai em TF-IDF se indisponivel.\n"
    "let defesas_anteriores = null;\n"
    "\n"
    "if (ADMIN_TOKEN && tipoRaw && SAFE_TIPO_RX.test(tipoRaw)) {\n"
    "  try {\n"
    "    const pedidosArr = Array.isArray(dados.pedidos) ? dados.pedidos : [];\n"
    "    const rag_resp = await __FETCH(BACKEND_URL + '/api/rag/defesas-similares', {\n"
    "      method: 'POST',\n"
    "      headers: { 'Authorization': 'Bearer ' + ADMIN_TOKEN, 'Content-Type': 'application/json' },\n"
    "      body: JSON.stringify({\n"
    "        tipo_acao: tipoRaw,\n"
    "        numero_processo: numeroRaw,\n"
    "        fatos: dados.fatos_resumo || '',\n"
    "        pedidos: pedidosArr,\n"
    "      }),\n"
    "    });\n"
    "    if (rag_resp.ok) {\n"
    "      const rag_data = await rag_resp.json();\n"
    "      // sucesso ou sem_resultados -> usa resultado semantico\n"
    "      // embedding_indisponivel / erro -> defesas_anteriores continua null -> cai no TF-IDF\n"
    "      if (rag_data && (rag_data.status === 'sucesso' || rag_data.status === 'sem_resultados')) {\n"
    "        defesas_anteriores = rag_data;\n"
    "      }\n"
    "    }\n"
    "  } catch (_) { /* falha de rede -> TF-IDF */ }\n"
    "}\n"
    "\n"
    "// Fallback TF-IDF (comportamento original inalterado)\n"
    "if (!defesas_anteriores) {\n"
    "  const SUPABASE_URL = readEnv('SUPABASE_URL');\n"
    "  const SUPABASE_KEY = readEnv('SUPABASE_PUBLISHABLE_KEY') || readEnv('SUPABASE_ANON_KEY') || readEnv('SUPABASE_SERVICE_ROLE_KEY');\n"
    "\n"
    "  if (!SUPABASE_URL || !SUPABASE_KEY) {\n"
    "    defesas_anteriores = { status: 'sem_credenciais', detalhe: 'SUPABASE nao configurado', casos: [], total: 0 };\n"
    "  } else if (!tipoRaw || !SAFE_TIPO_RX.test(tipoRaw) || !SAFE_NUMERO_RX.test(numeroRaw)) {\n"
    "    defesas_anteriores = { status: 'input_invalido', detalhe: 'tipo_acao/numero_processo invalidos', casos: [], total: 0 };\n"
    "  } else {\n"
    "    function tokenize(text) {\n"
    "      return (text || '').toLowerCase()\n"
    "        .normalize('NFD').replace(/\\p{Diacritic}/gu, '')\n"
    "        .replace(/[^a-z0-9\\s]/g, ' ')\n"
    "        .split(/\\s+/).filter(t => t.length > 2);\n"
    "    }\n"
    "    function buildTF(tokens) {\n"
    "      const tf = {};\n"
    "      for (const t of tokens) tf[t] = (tf[t] || 0) + 1;\n"
    "      const total = tokens.length || 1;\n"
    "      for (const t in tf) tf[t] /= total;\n"
    "      return tf;\n"
    "    }\n"
    "    function cosineSimilarity(tfA, tfB) {\n"
    "      let dot = 0, normA = 0, normB = 0;\n"
    "      for (const t in tfA) { normA += tfA[t]*tfA[t]; if (tfB[t]) dot += tfA[t]*tfB[t]; }\n"
    "      for (const t in tfB) normB += tfB[t]*tfB[t];\n"
    "      if (!normA || !normB) return 0;\n"
    "      return dot / (Math.sqrt(normA) * Math.sqrt(normB));\n"
    "    }\n"
    "    function scoreCase(c, queryTF) {\n"
    "      const caseTF = buildTF(tokenize((c.fatos || '') + ' ' + (c.pedido_autor || '')));\n"
    "      const sim = cosineSimilarity(queryTF, caseTF);\n"
    "      const fb = c.feedback_util === true ? 1.0 : c.feedback_util === false ? 0.0 : 0.5;\n"
    "      return 0.6 * sim + 0.4 * fb;\n"
    "    }\n"
    "    const tipo = encodeURIComponent(tipoRaw);\n"
    "    const numero = encodeURIComponent(numeroRaw);\n"
    "    const url = SUPABASE_URL + '/rest/v1/contestacoes'\n"
    "      + '?select=numero_processo,tipo_acao,fatos,pedido_autor,n8n_resposta,status,feedback_util,criado_em'\n"
    "      + '&status=eq.ok'\n"
    "      + '&tipo_acao=eq.' + tipo\n"
    "      + '&numero_processo=neq.' + numero\n"
    "      + '&order=criado_em.desc&limit=10';\n"
    "    try {\n"
    "      const resp = await __FETCH(url, {\n"
    "        headers: { 'apikey': SUPABASE_KEY, 'Authorization': 'Bearer ' + SUPABASE_KEY, 'Content-Type': 'application/json' }\n"
    "      });\n"
    "      if (!resp.ok) {\n"
    "        const body = await resp.text().catch(() => '');\n"
    "        defesas_anteriores = { status: 'erro_http', detalhe: 'HTTP ' + resp.status + ': ' + body.slice(0,150), casos: [], total: 0 };\n"
    "      } else {\n"
    "        const rows = await resp.json();\n"
    "        if (!rows || rows.length === 0) {\n"
    "          defesas_anteriores = { status: 'sem_resultados', detalhe: 'nenhuma defesa anterior', casos: [], total: 0 };\n"
    "        } else {\n"
    "          const queryTF = buildTF(tokenize((dados.fatos_resumo || '') + ' ' + (dados.pedidos || []).join(' ')));\n"
    "          const casosRaw = rows.map(row => {\n"
    "            const minuta = (row.n8n_resposta || {}).minuta || {};\n"
    "            return {\n"
    "              numero_processo: row.numero_processo,\n"
    "              tipo_acao: row.tipo_acao,\n"
    "              fatos: row.fatos || '',\n"
    "              pedido_autor: row.pedido_autor || '',\n"
    "              feedback_util: row.feedback_util,\n"
    "              fatos_resumo: (row.fatos || '').slice(0, 500),\n"
    "              pedido_autor_resumo: (row.pedido_autor || '').slice(0, 300),\n"
    "              tese_central: minuta.tese_central || '',\n"
    "              resumo_estrategico: minuta.resumo_estrategico || '',\n"
    "              fundamentos_curtos: (minuta.fundamentos || '').slice(0, 1500),\n"
    "              riscos: (minuta.riscos || []).slice(0, 3),\n"
    "              criado_em: row.criado_em,\n"
    "              _score: 0\n"
    "            };\n"
    "          });\n"
    "          for (const c of casosRaw) c._score = scoreCase(c, queryTF);\n"
    "          casosRaw.sort((a, b) => b._score - a._score);\n"
    "          const relevantes = casosRaw.filter(c => c._score >= 0.1);\n"
    "          const casos = (relevantes.length > 0 ? relevantes : casosRaw).slice(0, 3);\n"
    "          for (const c of casos) { delete c._score; delete c.fatos; delete c.pedido_autor; delete c.feedback_util; }\n"
    "          defesas_anteriores = {\n"
    "            status: 'sucesso',\n"
    "            detalhe: casos.length + ' defesa(s) selecionada(s) de ' + rows.length + ' (TF-IDF fallback)',\n"
    "            casos, total: casos.length\n"
    "          };\n"
    "        }\n"
    "      }\n"
    "    } catch (e) {\n"
    "      defesas_anteriores = { status: e.__TIMED_OUT === true ? 'timeout_8s' : 'erro_conexao', detalhe: e.message, casos: [], total: 0 };\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
    "// Buscar exemplares few-shot (inalterado)\n"
    "let exemplares_fewshot = [];\n"
    "if (ADMIN_TOKEN && tipoRaw) {\n"
    "  try {\n"
    "    const ex_resp = await __FETCH(\n"
    "      BACKEND_URL + '/api/admin/exemplares?tipo_acao=' + encodeURIComponent(tipoRaw),\n"
    "      { headers: { 'Authorization': 'Bearer ' + ADMIN_TOKEN, 'Content-Type': 'application/json' } });\n"
    "    if (ex_resp.ok) {\n"
    "      const ex_data = await ex_resp.json();\n"
    "      exemplares_fewshot = ex_data.exemplares || [];\n"
    "    }\n"
    "  } catch (_) {}\n"
    "}\n"
    "\n"
    "return [{ json: { ...envelope, defesas_anteriores, exemplares_fewshot } }];\n"
)

with open(WF_PATH, "r", encoding="utf-8") as f:
    wf = json.load(f)

updated = False
for node in wf["nodes"]:
    if node["id"] == "node-buscar-defesas-peticao":
        node["parameters"]["jsCode"] = NEW_JS
        updated = True
        break

if not updated:
    print("ERRO: node node-buscar-defesas-peticao nao encontrado!", file=sys.stderr)
    sys.exit(1)

wf["updatedAt"] = "2026-05-14T00:00:00.000Z"
desc = wf.get("description", "")
if "PR6 #4" not in desc:
    wf["description"] = desc.rstrip(".") + " | PR6 #4: RAG Semantico (pgvector <=>), fallback TF-IDF."

with open(WF_PATH, "w", encoding="utf-8") as f:
    json.dump(wf, f, ensure_ascii=False, indent=2)

print("OK - node 'Buscar Defesas Anteriores' atualizado com RAG semantico + fallback TF-IDF.")
